# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_pages.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainPages(object):
    def setupUi(self, MainPages):
        MainPages.setObjectName("MainPages")
        MainPages.resize(860, 600)
        self.main_pages_layout = QtWidgets.QVBoxLayout(MainPages)
        self.main_pages_layout.setContentsMargins(5, 5, 5, 5)
        self.main_pages_layout.setSpacing(0)
        self.main_pages_layout.setObjectName("main_pages_layout")
        self.pages = QtWidgets.QStackedWidget(MainPages)
        self.pages.setObjectName("pages")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setStyleSheet("font-size: 14pt;")
        self.page_1.setObjectName("page_1")
        self.page_1_layout = QtWidgets.QVBoxLayout(self.page_1)
        self.page_1_layout.setContentsMargins(5, 5, 5, 5)
        self.page_1_layout.setSpacing(5)
        self.page_1_layout.setObjectName("page_1_layout")
        self.pages.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.page_2_layout = QtWidgets.QVBoxLayout(self.page_2)
        self.page_2_layout.setContentsMargins(5, 5, 5, 5)
        self.page_2_layout.setSpacing(5)
        self.page_2_layout.setObjectName("page_2_layout")
        self.pages.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.page_3_layout = QtWidgets.QVBoxLayout(self.page_3)
        self.page_3_layout.setObjectName("page_3_layout")
        self.empty_page_label = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.empty_page_label.setFont(font)
        self.empty_page_label.setAlignment(QtCore.Qt.AlignCenter)
        self.empty_page_label.setObjectName("empty_page_label")
        self.page_3_layout.addWidget(self.empty_page_label)
        self.pages.addWidget(self.page_3)
        self.main_pages_layout.addWidget(self.pages)

        self.retranslateUi(MainPages)
        self.pages.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainPages)

    def retranslateUi(self, MainPages):
        _translate = QtCore.QCoreApplication.translate
        MainPages.setWindowTitle(_translate("MainPages", "Form"))
        self.empty_page_label.setText(_translate("MainPages", "Empty Page"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainPages = QtWidgets.QWidget()
    ui = Ui_MainPages()
    ui.setupUi(MainPages)
    MainPages.show()
    sys.exit(app.exec_())
